events {}

http {
    server {
        listen 80;

        # API request -> Spring Boot
        location /api/ {
            proxy_pass http://backend-app:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Web request -> Frontend app (container FE serve qua Nginx port 80)
        location / {
            proxy_pass http://frontend-app:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
