version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: gateway-nginx-prod
    ports:
      - "80:80"
      # - "443:443" # bật khi cấu hình TLS/SSL
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-app
      - backend-app
    networks:
      - app-network

  frontend-app:
    image: ${DOCKER_HUB_USER}/qlncc-fe:latest
    container_name: my-nuxt-app-prod
    restart: unless-stopped
    networks:
      - app-network

  backend-app:
    image: ${DOCKER_HUB_USER}/qlncc-be:latest
    container_name: my-spring-app-prod
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/qlncc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: my-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: qlncc
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: my-redis-prod
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
